name: DuelWorld
author: thomi100
version: 1.0.0
website: http://thomi100.net
description: DuelWorld

main: net.thomi100.DuelWorlds

depends: [BountifulAPI, HolographicDisplays, ThomiAPI]

commands:
  duel:
    description: DuelWorld
    aliases: [dw, duelworld]
    usage: /duel